package frame;


import PD1_Dimbovskis.User;
import java.util.List;
import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vadims Dimbovskis PR-21
 */
public class MainTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestingSystem
     */
    public MainTestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRegDialog1 = new javax.swing.JDialog();
        jRegistrationPanel2 = new javax.swing.JPanel();
        jRegLabel1 = new javax.swing.JLabel();
        jNameLabel2 = new javax.swing.JLabel();
        jSurnameLabel5 = new javax.swing.JLabel();
        jUsernameLabel7 = new javax.swing.JLabel();
        jPasswordLabel8 = new javax.swing.JLabel();
        jRepeatpasswordLabel9 = new javax.swing.JLabel();
        jNameTextField1 = new javax.swing.JTextField();
        jSurnameTextField4 = new javax.swing.JTextField();
        jUsernameTextField5 = new javax.swing.JTextField();
        jPasswordTextField6 = new javax.swing.JTextField();
        jRepeatpasswordTextField7 = new javax.swing.JTextField();
        jRegisterButton4 = new javax.swing.JButton();
        jTestSwDialog = new javax.swing.JDialog();
        jTestselectionPanel4 = new javax.swing.JPanel();
        jTestselectionLabel1 = new javax.swing.JLabel();
        jTest1Button1 = new javax.swing.JButton();
        jTest2Button2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jResultPanel4 = new javax.swing.JPanel();
        jResultLabel10 = new javax.swing.JLabel();
        jProcentLabel1 = new javax.swing.JLabel();
        jMarkLabel2 = new javax.swing.JLabel();
        jAgainButton1 = new javax.swing.JButton();
        jEndButton2 = new javax.swing.JButton();
        jTestLabel3 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jResultPanel5 = new javax.swing.JPanel();
        jResultLabel11 = new javax.swing.JLabel();
        jProcentLabel2 = new javax.swing.JLabel();
        jMarkLabel3 = new javax.swing.JLabel();
        jAgainButton2 = new javax.swing.JButton();
        jEndButton3 = new javax.swing.JButton();
        jTestLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jUsernameTextField2 = new javax.swing.JTextField();
        jUsernameLabel3 = new javax.swing.JLabel();
        jPasswordTextField3 = new javax.swing.JTextField();
        jPasswordLabel4 = new javax.swing.JLabel();
        jRegisterButton1 = new javax.swing.JButton();
        jAuthLabel6 = new javax.swing.JLabel();
        jLoginButton2 = new javax.swing.JButton();

        jRegistrationPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRegLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRegLabel1.setText("Reģistrācija");

        jNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNameLabel2.setText("Vārds:");

        jSurnameLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSurnameLabel5.setText("Uzvārds:");

        jUsernameLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jUsernameLabel7.setText("Lietotājvārds:");

        jPasswordLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordLabel8.setText("Parole:");

        jRepeatpasswordLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRepeatpasswordLabel9.setText("Parole(Atkartoti):");

        jNameTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jSurnameTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSurnameTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSurnameTextField4ActionPerformed(evt);
            }
        });

        jUsernameTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPasswordTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jRepeatpasswordTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jRegisterButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRegisterButton4.setText("Reģistrēties");
        jRegisterButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRegistrationPanel2Layout = new javax.swing.GroupLayout(jRegistrationPanel2);
        jRegistrationPanel2.setLayout(jRegistrationPanel2Layout);
        jRegistrationPanel2Layout.setHorizontalGroup(
            jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationPanel2Layout.createSequentialGroup()
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jRegLabel1)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRepeatpasswordLabel9)
                            .addComponent(jPasswordLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUsernameLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSurnameLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNameLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRepeatpasswordTextField7)
                            .addComponent(jPasswordTextField6)
                            .addComponent(jUsernameTextField5)
                            .addComponent(jSurnameTextField4)
                            .addComponent(jNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jRegisterButton4)
                .addGap(98, 98, 98))
        );
        jRegistrationPanel2Layout.setVerticalGroup(
            jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegLabel1)
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel2)
                    .addComponent(jNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSurnameLabel5)
                    .addComponent(jSurnameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel7)
                    .addComponent(jUsernameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordLabel8)
                    .addComponent(jPasswordTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRepeatpasswordLabel9)
                    .addComponent(jRepeatpasswordTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jRegisterButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jRegDialog1Layout = new javax.swing.GroupLayout(jRegDialog1.getContentPane());
        jRegDialog1.getContentPane().setLayout(jRegDialog1Layout);
        jRegDialog1Layout.setHorizontalGroup(
            jRegDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jRegDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jRegDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRegistrationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jRegDialog1Layout.setVerticalGroup(
            jRegDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jRegDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jRegDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRegistrationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTestselectionPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jTestselectionPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTestselectionLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jTestselectionLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jTestselectionLabel1.setText("Izvēlieties testu");

        jTest1Button1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTest1Button1.setText("Test1");
        jTest1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTest1Button1ActionPerformed(evt);
            }
        });

        jTest2Button2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTest2Button2.setText("Test2");
        jTest2Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTest2Button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTestselectionPanel4Layout = new javax.swing.GroupLayout(jTestselectionPanel4);
        jTestselectionPanel4.setLayout(jTestselectionPanel4Layout);
        jTestselectionPanel4Layout.setHorizontalGroup(
            jTestselectionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTestselectionPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTest1Button1)
                .addGap(50, 50, 50)
                .addComponent(jTest2Button2)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTestselectionPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTestselectionLabel1)
                .addGap(55, 55, 55))
        );
        jTestselectionPanel4Layout.setVerticalGroup(
            jTestselectionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTestselectionPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTestselectionLabel1)
                .addGap(30, 30, 30)
                .addGroup(jTestselectionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTest1Button1)
                    .addComponent(jTest2Button2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTestSwDialogLayout = new javax.swing.GroupLayout(jTestSwDialog.getContentPane());
        jTestSwDialog.getContentPane().setLayout(jTestSwDialogLayout);
        jTestSwDialogLayout.setHorizontalGroup(
            jTestSwDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTestSwDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTestselectionPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jTestSwDialogLayout.setVerticalGroup(
            jTestSwDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTestselectionPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("1");

        jLabel6.setText("2");

        jLabel7.setText("3");

        jLabel8.setText("4");

        jLabel9.setText("5");

        jLabel10.setText("6");

        jLabel11.setText("7");

        jLabel12.setText("8");

        jLabel13.setText("9");

        jLabel14.setText("10");

        jButton14.setBackground(new java.awt.Color(255, 51, 51));
        jButton14.setText("Pabeigt testu");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });

        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField14FocusLost(evt);
            }
        });

        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField17FocusLost(evt);
            }
        });

        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField18FocusLost(evt);
            }
        });

        jTextField20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField20FocusLost(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Spēks, kas piesaista objektus viens otram.");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Elektromagnētiskais lauks.");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Procesa rezultāts, kurā gaisma tiek izkliedēta.");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Spēks vienmēr ir vienāds ar masu reizinātu ar paātrinājumu.");

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Enerģija nevar tikt radīta vai iznīcināta.");

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Katrs ķermenis saglabā savu kustības stāvokli, ja uz to nedarbojas ārējs spēks.");

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Spēja pārnest siltumu.");

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Spēja absorbēt gaismu.");

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Elektriskā strāva, kas pārvietojas materiālā.");

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Spēks, kas piesaista objektus viens otram.");

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Enerģijas forma, kas nevar tikt radīta vai iznīcināta.");

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("Kustība elektriskajiem lādiņiem caur vadītāju.");

        jRadioButton13.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("Ātrums, ar kādu objekts kustās vakuumā.");

        jRadioButton14.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("Ātrums, kas nepieciešams, lai izvairītos no Zemes gravitācijas.");

        jLabel76.setText("1.Spēks, kas piesaista objektus viens otram.");

        jLabel77.setText("2.Spēks, kas darbojas pret kustību.");

        jLabel1.setText("Test1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton6)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(398, 398, 398))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jLabel7)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton9)
                                    .addComponent(jRadioButton11)
                                    .addComponent(jLabel11)
                                    .addComponent(jRadioButton14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel76)
                                    .addComponent(jRadioButton12)
                                    .addComponent(jRadioButton10)
                                    .addComponent(jLabel10)
                                    .addComponent(jRadioButton13)
                                    .addComponent(jLabel77)
                                    .addComponent(jRadioButton7))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(jRadioButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton8))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton13))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel77)
                        .addGap(16, 16, 16)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("1");

        jLabel16.setText("2");

        jLabel17.setText("3");

        jLabel18.setText("4");

        jLabel19.setText("5");

        jLabel20.setText("6");

        jLabel21.setText("7");

        jLabel22.setText("8");

        jLabel23.setText("9");

        jLabel24.setText("10");

        jButton15.setBackground(new java.awt.Color(255, 51, 51));
        jButton15.setText("Pabeigt testu");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField15FocusLost(evt);
            }
        });

        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField16FocusLost(evt);
            }
        });

        jTextField19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField19FocusLost(evt);
            }
        });

        jTextField21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField21FocusLost(evt);
            }
        });

        jTextField22.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField22FocusLost(evt);
            }
        });

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("Spēks, kas piesaista objektus viens otram.");

        jRadioButton16.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Elektromagnētiskais lauks.");

        jRadioButton17.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("Procesa rezultāts, kurā gaisma tiek izkliedēta.");

        jRadioButton18.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("Spēks vienmēr ir vienāds ar masu reizinātu ar paātrinājumu.");

        jRadioButton19.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("Enerģija nevar tikt radīta vai iznīcināta.");

        jRadioButton20.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("Katrs ķermenis saglabā savu kustības stāvokli, ja uz to nedarbojas ārējs spēks.");

        jRadioButton21.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setText("Spēja pārnest siltumu.");

        jRadioButton22.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setText("Spēja absorbēt gaismu.");

        jRadioButton23.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setText("Elektriskā strāva, kas pārvietojas materiālā.");

        jRadioButton24.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setText("Spēks, kas piesaista objektus viens otram.");

        jRadioButton25.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton25.setText("Enerģijas forma, kas nevar tikt radīta vai iznīcināta.");

        jRadioButton26.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setText("Kustība elektriskajiem lādiņiem caur vadītāju.");

        jRadioButton27.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setText("Ātrums, ar kādu objekts kustās vakuumā.");

        jRadioButton28.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setText("Ātrums, kas nepieciešams, lai izvairītos no Zemes gravitācijas.");

        jLabel78.setText("1.Spēks, kas piesaista objektus viens otram.");

        jLabel79.setText("2.Spēks, kas darbojas pret kustību.");

        jLabel2.setText("Test2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton20)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(398, 398, 398))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton17)
                                    .addComponent(jRadioButton16)
                                    .addComponent(jRadioButton15)
                                    .addComponent(jLabel17)
                                    .addComponent(jRadioButton19)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jRadioButton22)
                                    .addComponent(jRadioButton23)
                                    .addComponent(jRadioButton25)
                                    .addComponent(jLabel21)
                                    .addComponent(jRadioButton28)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel78)
                                    .addComponent(jRadioButton26)
                                    .addComponent(jRadioButton24)
                                    .addComponent(jLabel20)
                                    .addComponent(jRadioButton27)
                                    .addComponent(jLabel79)
                                    .addComponent(jRadioButton21))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(7, 7, 7)
                        .addComponent(jRadioButton21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton22))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton27))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel78)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel79)
                        .addGap(16, 16, 16)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton15)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jResultPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jResultLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jResultLabel10.setText("Rezultāti");

        jProcentLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jProcentLabel1.setText("Procenti: x %");

        jMarkLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMarkLabel2.setText("Atzīme: x p.");

        jAgainButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAgainButton1.setText("Mēģiniet vēlreiz");
        jAgainButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgainButton1ActionPerformed(evt);
            }
        });

        jEndButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEndButton2.setText("Pabeigt");
        jEndButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEndButton2ActionPerformed(evt);
            }
        });

        jTestLabel3.setText("Test1");

        javax.swing.GroupLayout jResultPanel4Layout = new javax.swing.GroupLayout(jResultPanel4);
        jResultPanel4.setLayout(jResultPanel4Layout);
        jResultPanel4Layout.setHorizontalGroup(
            jResultPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAgainButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jEndButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jResultPanel4Layout.createSequentialGroup()
                .addGroup(jResultPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanel4Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jResultPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jMarkLabel2)
                            .addComponent(jProcentLabel1)))
                    .addGroup(jResultPanel4Layout.createSequentialGroup()
                        .addComponent(jTestLabel3)
                        .addGap(75, 75, 75)
                        .addComponent(jResultLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jResultPanel4Layout.setVerticalGroup(
            jResultPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanel4Layout.createSequentialGroup()
                .addGroup(jResultPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jResultLabel10))
                    .addComponent(jTestLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProcentLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMarkLabel2)
                .addGap(24, 24, 24)
                .addGroup(jResultPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgainButton1)
                    .addComponent(jEndButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jResultPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jResultPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jResultPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jResultLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jResultLabel11.setText("Rezultāti");

        jProcentLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jProcentLabel2.setText("Procenti: x %");

        jMarkLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMarkLabel3.setText("Atzīme: x p.");

        jAgainButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAgainButton2.setText("Mēģiniet vēlreiz");
        jAgainButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgainButton2ActionPerformed(evt);
            }
        });

        jEndButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEndButton3.setText("Pabeigt");
        jEndButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEndButton3ActionPerformed(evt);
            }
        });

        jTestLabel4.setText("Test2");

        javax.swing.GroupLayout jResultPanel5Layout = new javax.swing.GroupLayout(jResultPanel5);
        jResultPanel5.setLayout(jResultPanel5Layout);
        jResultPanel5Layout.setHorizontalGroup(
            jResultPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAgainButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jEndButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jResultPanel5Layout.createSequentialGroup()
                .addGroup(jResultPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanel5Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jResultPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jMarkLabel3)
                            .addComponent(jProcentLabel2)))
                    .addGroup(jResultPanel5Layout.createSequentialGroup()
                        .addComponent(jTestLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(jResultLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jResultPanel5Layout.setVerticalGroup(
            jResultPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanel5Layout.createSequentialGroup()
                .addGroup(jResultPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jResultLabel11))
                    .addComponent(jTestLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProcentLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMarkLabel3)
                .addGap(24, 24, 24)
                .addGroup(jResultPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgainButton2)
                    .addComponent(jEndButton3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jResultPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jResultPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUsernameTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jUsernameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jUsernameLabel3.setText("Lietotāvārds:");

        jPasswordTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPasswordLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordLabel4.setText("Parole:");

        jRegisterButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRegisterButton1.setText("Reģistrēties");
        jRegisterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButton1ActionPerformed(evt);
            }
        });

        jAuthLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jAuthLabel6.setText("Autorizācija");
        jAuthLabel6.setToolTipText("");

        jLoginButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLoginButton2.setText("Pieslēgties");
        jLoginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUsernameLabel3)
                            .addComponent(jPasswordLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jUsernameTextField2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRegisterButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLoginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jAuthLabel6)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAuthLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel3)
                    .addComponent(jUsernameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterButton1)
                    .addComponent(jLoginButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegisterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButton1ActionPerformed
        jRegDialog1.pack();
        jRegDialog1.setLocationRelativeTo(this);
        jRegDialog1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jRegisterButton1ActionPerformed

    private void jSurnameTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSurnameTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSurnameTextField4ActionPerformed

    private void jLoginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton2ActionPerformed
        jTestSwDialog.setVisible(true);
        jPanel1.setVisible(false);       
    }//GEN-LAST:event_jLoginButton2ActionPerformed

    private void jTest1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTest1Button1ActionPerformed
        jDialog1.setVisible(true);
        jTestSwDialog.setVisible(false); 
    }//GEN-LAST:event_jTest1Button1ActionPerformed

    private void jTest2Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTest2Button2ActionPerformed
        jDialog2.setVisible(true);
        jTestSwDialog.setVisible(false);  
    }//GEN-LAST:event_jTest2Button2ActionPerformed

    private void jRegisterButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButton4ActionPerformed
        jTestSwDialog.setVisible(true);
        jRegDialog1.setVisible(false);  
    }//GEN-LAST:event_jRegisterButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jDialog3.setVisible(true);
        jDialog1.setVisible(false); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost

    }//GEN-LAST:event_jTextField13FocusLost

    private void jTextField14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusLost

    }//GEN-LAST:event_jTextField14FocusLost

    private void jTextField17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField17FocusLost

    }//GEN-LAST:event_jTextField17FocusLost

    private void jTextField18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusLost

    }//GEN-LAST:event_jTextField18FocusLost

    private void jTextField20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusLost

    }//GEN-LAST:event_jTextField20FocusLost

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jDialog4.setVisible(true);
        jDialog2.setVisible(false); 
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField15FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15FocusLost

    private void jTextField16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField16FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16FocusLost

    private void jTextField19FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField19FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19FocusLost

    private void jTextField21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField21FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21FocusLost

    private void jTextField22FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField22FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22FocusLost

    private void jAgainButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgainButton1ActionPerformed
        jDialog2.setVisible(true); 
        jDialog3.setVisible(false); 
    }//GEN-LAST:event_jAgainButton1ActionPerformed

    private void jEndButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEndButton2ActionPerformed
        jDialog3.setVisible(false);
    }//GEN-LAST:event_jEndButton2ActionPerformed

    private void jEndButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEndButton3ActionPerformed

        jDialog4.setVisible(false); 
    }//GEN-LAST:event_jEndButton3ActionPerformed

    private void jAgainButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgainButton2ActionPerformed
                jDialog2.setVisible(true); 
        jDialog4.setVisible(false); 
        
    }//GEN-LAST:event_jAgainButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainTestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgainButton1;
    private javax.swing.JButton jAgainButton2;
    private javax.swing.JLabel jAuthLabel6;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JButton jEndButton2;
    private javax.swing.JButton jEndButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton2;
    private javax.swing.JLabel jMarkLabel2;
    private javax.swing.JLabel jMarkLabel3;
    private javax.swing.JLabel jNameLabel2;
    private javax.swing.JTextField jNameTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPasswordLabel4;
    private javax.swing.JLabel jPasswordLabel8;
    private javax.swing.JTextField jPasswordTextField3;
    private javax.swing.JTextField jPasswordTextField6;
    private javax.swing.JLabel jProcentLabel1;
    private javax.swing.JLabel jProcentLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JDialog jRegDialog1;
    private javax.swing.JLabel jRegLabel1;
    private javax.swing.JButton jRegisterButton1;
    private javax.swing.JButton jRegisterButton4;
    private javax.swing.JPanel jRegistrationPanel2;
    private javax.swing.JLabel jRepeatpasswordLabel9;
    private javax.swing.JTextField jRepeatpasswordTextField7;
    private javax.swing.JLabel jResultLabel10;
    private javax.swing.JLabel jResultLabel11;
    private javax.swing.JPanel jResultPanel4;
    private javax.swing.JPanel jResultPanel5;
    private javax.swing.JLabel jSurnameLabel5;
    private javax.swing.JTextField jSurnameTextField4;
    private javax.swing.JButton jTest1Button1;
    private javax.swing.JButton jTest2Button2;
    private javax.swing.JLabel jTestLabel3;
    private javax.swing.JLabel jTestLabel4;
    private javax.swing.JDialog jTestSwDialog;
    private javax.swing.JLabel jTestselectionLabel1;
    private javax.swing.JPanel jTestselectionPanel4;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JLabel jUsernameLabel3;
    private javax.swing.JLabel jUsernameLabel7;
    private javax.swing.JTextField jUsernameTextField2;
    private javax.swing.JTextField jUsernameTextField5;
    // End of variables declaration//GEN-END:variables

}
