
import PD1_Dimbovskis.User;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vadims Dimbovskis PR-21
 */
public class TestingSystem extends javax.swing.JFrame {

    /**
     * Creates new form TestingSystem
     */
    public TestingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jResultPanel3 = new javax.swing.JPanel();
        jResultLabel10 = new javax.swing.JLabel();
        jProcentLabel1 = new javax.swing.JLabel();
        jMarkLabel2 = new javax.swing.JLabel();
        jAgainButton1 = new javax.swing.JButton();
        jEndButton2 = new javax.swing.JButton();
        jTestLabel3 = new javax.swing.JLabel();
        jRegistrationPanel2 = new javax.swing.JPanel();
        jRegLabel1 = new javax.swing.JLabel();
        jNameLabel2 = new javax.swing.JLabel();
        jSurnameLabel5 = new javax.swing.JLabel();
        jUsernameLabel7 = new javax.swing.JLabel();
        jPasswordLabel8 = new javax.swing.JLabel();
        jRepeatpasswordLabel9 = new javax.swing.JLabel();
        jNameTextField1 = new javax.swing.JTextField();
        jSurnameTextField4 = new javax.swing.JTextField();
        jUsernameTextField5 = new javax.swing.JTextField();
        jPasswordTextField6 = new javax.swing.JTextField();
        jRepeatpasswordTextField7 = new javax.swing.JTextField();
        jRegisterButton4 = new javax.swing.JButton();
        jTest1Dialog1 = new javax.swing.JDialog();
        jTest1Panel5 = new javax.swing.JPanel();
        jQuestionLabel10 = new javax.swing.JLabel();
        jAnswer11RadioButton1 = new javax.swing.JRadioButton();
        jAnswer12RadioButton2 = new javax.swing.JRadioButton();
        jAnswer13RadioButton3 = new javax.swing.JRadioButton();
        jAnswer14RadioButton4 = new javax.swing.JRadioButton();
        jTest1Label1 = new javax.swing.JLabel();
        buttonTest1Group1 = new javax.swing.ButtonGroup();
        jTest2Dialog2 = new javax.swing.JDialog();
        jTest2Panel6 = new javax.swing.JPanel();
        jQuestionLabel11 = new javax.swing.JLabel();
        jAnswer21RadioButton1 = new javax.swing.JRadioButton();
        jAnswer22RadioButton2 = new javax.swing.JRadioButton();
        jAnswer23RadioButton3 = new javax.swing.JRadioButton();
        jAnswer24RadioButton4 = new javax.swing.JRadioButton();
        jTest2Label2 = new javax.swing.JLabel();
        buttonTest2Group2 = new javax.swing.ButtonGroup();
        jTestselectionPanel4 = new javax.swing.JPanel();
        jTestselectionLabel1 = new javax.swing.JLabel();
        jTest1Button1 = new javax.swing.JButton();
        jTest2Button2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jUsernameTextField2 = new javax.swing.JTextField();
        jUsernameLabel3 = new javax.swing.JLabel();
        jPasswordTextField3 = new javax.swing.JTextField();
        jPasswordLabel4 = new javax.swing.JLabel();
        jRegisterButton1 = new javax.swing.JButton();
        jAuthLabel6 = new javax.swing.JLabel();
        jLoginButton2 = new javax.swing.JButton();

        jResultPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jResultLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jResultLabel10.setText("Rezultāti");

        jProcentLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jProcentLabel1.setText("Procenti: x %");

        jMarkLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMarkLabel2.setText("Atzīme: x p.");

        jAgainButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAgainButton1.setText("Mēģiniet vēlreiz");

        jEndButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEndButton2.setText("Pabeigt");

        jTestLabel3.setText("Test1/2");

        javax.swing.GroupLayout jResultPanel3Layout = new javax.swing.GroupLayout(jResultPanel3);
        jResultPanel3.setLayout(jResultPanel3Layout);
        jResultPanel3Layout.setHorizontalGroup(
            jResultPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAgainButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jEndButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jResultPanel3Layout.createSequentialGroup()
                .addGroup(jResultPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jResultPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jMarkLabel2)
                            .addComponent(jProcentLabel1)))
                    .addGroup(jResultPanel3Layout.createSequentialGroup()
                        .addComponent(jTestLabel3)
                        .addGap(75, 75, 75)
                        .addComponent(jResultLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jResultPanel3Layout.setVerticalGroup(
            jResultPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanel3Layout.createSequentialGroup()
                .addGroup(jResultPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jResultLabel10))
                    .addComponent(jTestLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProcentLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMarkLabel2)
                .addGap(24, 24, 24)
                .addGroup(jResultPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgainButton1)
                    .addComponent(jEndButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jRegistrationPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRegLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRegLabel1.setText("Reģistrācija");

        jNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNameLabel2.setText("Vārds:");

        jSurnameLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSurnameLabel5.setText("Uzvārds:");

        jUsernameLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jUsernameLabel7.setText("Lietotājvārds:");

        jPasswordLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordLabel8.setText("Parole:");

        jRepeatpasswordLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRepeatpasswordLabel9.setText("Parole(Atkartoti):");

        jNameTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jSurnameTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSurnameTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSurnameTextField4ActionPerformed(evt);
            }
        });

        jUsernameTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPasswordTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jRepeatpasswordTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jRegisterButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRegisterButton4.setText("Reģistrēties");

        javax.swing.GroupLayout jRegistrationPanel2Layout = new javax.swing.GroupLayout(jRegistrationPanel2);
        jRegistrationPanel2.setLayout(jRegistrationPanel2Layout);
        jRegistrationPanel2Layout.setHorizontalGroup(
            jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationPanel2Layout.createSequentialGroup()
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jRegLabel1)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRepeatpasswordLabel9)
                            .addComponent(jPasswordLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUsernameLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSurnameLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNameLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRepeatpasswordTextField7)
                            .addComponent(jPasswordTextField6)
                            .addComponent(jUsernameTextField5)
                            .addComponent(jSurnameTextField4)
                            .addComponent(jNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegistrationPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jRegisterButton4)
                .addGap(98, 98, 98))
        );
        jRegistrationPanel2Layout.setVerticalGroup(
            jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRegLabel1)
                .addGap(18, 18, 18)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel2)
                    .addComponent(jNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSurnameLabel5)
                    .addComponent(jSurnameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel7)
                    .addComponent(jUsernameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordLabel8)
                    .addComponent(jPasswordTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRepeatpasswordLabel9)
                    .addComponent(jRepeatpasswordTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jRegisterButton4)
                .addContainerGap())
        );

        jTest1Panel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jQuestionLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jQuestionLabel10.setText("Jautājums");

        buttonTest1Group1.add(jAnswer11RadioButton1);
        jAnswer11RadioButton1.setText("jRadioButton1");

        buttonTest1Group1.add(jAnswer12RadioButton2);
        jAnswer12RadioButton2.setText("jRadioButton2");

        buttonTest1Group1.add(jAnswer13RadioButton3);
        jAnswer13RadioButton3.setText("jRadioButton3");
        jAnswer13RadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnswer13RadioButton3ActionPerformed(evt);
            }
        });

        buttonTest1Group1.add(jAnswer14RadioButton4);
        jAnswer14RadioButton4.setText("jRadioButton4");

        jTest1Label1.setText("Test1");

        javax.swing.GroupLayout jTest1Panel5Layout = new javax.swing.GroupLayout(jTest1Panel5);
        jTest1Panel5.setLayout(jTest1Panel5Layout);
        jTest1Panel5Layout.setHorizontalGroup(
            jTest1Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest1Panel5Layout.createSequentialGroup()
                .addGroup(jTest1Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTest1Panel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jTest1Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAnswer11RadioButton1)
                            .addComponent(jAnswer12RadioButton2)
                            .addComponent(jAnswer13RadioButton3)
                            .addComponent(jAnswer14RadioButton4)))
                    .addGroup(jTest1Panel5Layout.createSequentialGroup()
                        .addComponent(jTest1Label1)
                        .addGap(122, 122, 122)
                        .addComponent(jQuestionLabel10)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jTest1Panel5Layout.setVerticalGroup(
            jTest1Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest1Panel5Layout.createSequentialGroup()
                .addGroup(jTest1Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTest1Panel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jQuestionLabel10))
                    .addComponent(jTest1Label1))
                .addGap(41, 41, 41)
                .addComponent(jAnswer11RadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnswer12RadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnswer13RadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnswer14RadioButton4)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTest1Dialog1Layout = new javax.swing.GroupLayout(jTest1Dialog1.getContentPane());
        jTest1Dialog1.getContentPane().setLayout(jTest1Dialog1Layout);
        jTest1Dialog1Layout.setHorizontalGroup(
            jTest1Dialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest1Dialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTest1Panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTest1Dialog1Layout.setVerticalGroup(
            jTest1Dialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTest1Dialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTest1Panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTest2Panel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jQuestionLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jQuestionLabel11.setText("Jautājums");

        buttonTest2Group2.add(jAnswer21RadioButton1);
        jAnswer21RadioButton1.setText("jRadioButton1");

        buttonTest2Group2.add(jAnswer22RadioButton2);
        jAnswer22RadioButton2.setText("jRadioButton2");

        buttonTest2Group2.add(jAnswer23RadioButton3);
        jAnswer23RadioButton3.setText("jRadioButton3");
        jAnswer23RadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnswer23RadioButton3ActionPerformed(evt);
            }
        });

        buttonTest2Group2.add(jAnswer24RadioButton4);
        jAnswer24RadioButton4.setText("jRadioButton4");

        jTest2Label2.setText("Test2");

        javax.swing.GroupLayout jTest2Panel6Layout = new javax.swing.GroupLayout(jTest2Panel6);
        jTest2Panel6.setLayout(jTest2Panel6Layout);
        jTest2Panel6Layout.setHorizontalGroup(
            jTest2Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest2Panel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jTest2Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAnswer22RadioButton2)
                    .addComponent(jAnswer21RadioButton1)
                    .addComponent(jAnswer23RadioButton3)
                    .addComponent(jAnswer24RadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTest2Panel6Layout.createSequentialGroup()
                .addComponent(jTest2Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jQuestionLabel11)
                .addGap(163, 163, 163))
        );
        jTest2Panel6Layout.setVerticalGroup(
            jTest2Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest2Panel6Layout.createSequentialGroup()
                .addGroup(jTest2Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTest2Panel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jQuestionLabel11))
                    .addComponent(jTest2Label2))
                .addGap(41, 41, 41)
                .addComponent(jAnswer21RadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAnswer22RadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnswer23RadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAnswer24RadioButton4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTest2Dialog2Layout = new javax.swing.GroupLayout(jTest2Dialog2.getContentPane());
        jTest2Dialog2.getContentPane().setLayout(jTest2Dialog2Layout);
        jTest2Dialog2Layout.setHorizontalGroup(
            jTest2Dialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest2Dialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTest2Panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTest2Dialog2Layout.setVerticalGroup(
            jTest2Dialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTest2Dialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTest2Panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTestselectionPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jTestselectionPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTestselectionLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jTestselectionLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jTestselectionLabel1.setText("Izvēlieties testu");

        jTest1Button1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTest1Button1.setText("Test1");
        jTest1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTest1Button1ActionPerformed(evt);
            }
        });

        jTest2Button2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTest2Button2.setText("Test2");

        javax.swing.GroupLayout jTestselectionPanel4Layout = new javax.swing.GroupLayout(jTestselectionPanel4);
        jTestselectionPanel4.setLayout(jTestselectionPanel4Layout);
        jTestselectionPanel4Layout.setHorizontalGroup(
            jTestselectionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTestselectionPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTest1Button1)
                .addGap(50, 50, 50)
                .addComponent(jTest2Button2)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTestselectionPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTestselectionLabel1)
                .addGap(55, 55, 55))
        );
        jTestselectionPanel4Layout.setVerticalGroup(
            jTestselectionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTestselectionPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTestselectionLabel1)
                .addGap(30, 30, 30)
                .addGroup(jTestselectionPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTest1Button1)
                    .addComponent(jTest2Button2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUsernameTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jUsernameLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jUsernameLabel3.setText("Lietotāvārds:");

        jPasswordTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPasswordLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordLabel4.setText("Parole:");

        jRegisterButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRegisterButton1.setText("Reģistrēties");
        jRegisterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButton1ActionPerformed(evt);
            }
        });

        jAuthLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jAuthLabel6.setText("Autorizācija");
        jAuthLabel6.setToolTipText("");

        jLoginButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLoginButton2.setText("Pieslēgties");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUsernameLabel3)
                            .addComponent(jPasswordLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jUsernameTextField2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRegisterButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLoginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jAuthLabel6)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAuthLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel3)
                    .addComponent(jUsernameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterButton1)
                    .addComponent(jLoginButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegisterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterButton1ActionPerformed

    private void jSurnameTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSurnameTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSurnameTextField4ActionPerformed

    private void jAnswer23RadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnswer23RadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAnswer23RadioButton3ActionPerformed

    private void jAnswer13RadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnswer13RadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAnswer13RadioButton3ActionPerformed

    private void jTest1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTest1Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTest1Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingSystem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonTest1Group1;
    private javax.swing.ButtonGroup buttonTest2Group2;
    private javax.swing.JButton jAgainButton1;
    private javax.swing.JRadioButton jAnswer11RadioButton1;
    private javax.swing.JRadioButton jAnswer12RadioButton2;
    private javax.swing.JRadioButton jAnswer13RadioButton3;
    private javax.swing.JRadioButton jAnswer14RadioButton4;
    private javax.swing.JRadioButton jAnswer21RadioButton1;
    private javax.swing.JRadioButton jAnswer22RadioButton2;
    private javax.swing.JRadioButton jAnswer23RadioButton3;
    private javax.swing.JRadioButton jAnswer24RadioButton4;
    private javax.swing.JLabel jAuthLabel6;
    private javax.swing.JButton jEndButton2;
    private javax.swing.JButton jLoginButton2;
    private javax.swing.JLabel jMarkLabel2;
    private javax.swing.JLabel jNameLabel2;
    private javax.swing.JTextField jNameTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPasswordLabel4;
    private javax.swing.JLabel jPasswordLabel8;
    private javax.swing.JTextField jPasswordTextField3;
    private javax.swing.JTextField jPasswordTextField6;
    private javax.swing.JLabel jProcentLabel1;
    private javax.swing.JLabel jQuestionLabel10;
    private javax.swing.JLabel jQuestionLabel11;
    private javax.swing.JLabel jRegLabel1;
    private javax.swing.JButton jRegisterButton1;
    private javax.swing.JButton jRegisterButton4;
    private javax.swing.JPanel jRegistrationPanel2;
    private javax.swing.JLabel jRepeatpasswordLabel9;
    private javax.swing.JTextField jRepeatpasswordTextField7;
    private javax.swing.JLabel jResultLabel10;
    private javax.swing.JPanel jResultPanel3;
    private javax.swing.JLabel jSurnameLabel5;
    private javax.swing.JTextField jSurnameTextField4;
    private javax.swing.JButton jTest1Button1;
    private javax.swing.JDialog jTest1Dialog1;
    private javax.swing.JLabel jTest1Label1;
    private javax.swing.JPanel jTest1Panel5;
    private javax.swing.JButton jTest2Button2;
    private javax.swing.JDialog jTest2Dialog2;
    private javax.swing.JLabel jTest2Label2;
    private javax.swing.JPanel jTest2Panel6;
    private javax.swing.JLabel jTestLabel3;
    private javax.swing.JLabel jTestselectionLabel1;
    private javax.swing.JPanel jTestselectionPanel4;
    private javax.swing.JLabel jUsernameLabel3;
    private javax.swing.JLabel jUsernameLabel7;
    private javax.swing.JTextField jUsernameTextField2;
    private javax.swing.JTextField jUsernameTextField5;
    // End of variables declaration//GEN-END:variables
    private void addUser(String name, String login, String password, String repation){
    }
    private User findUser(String login, String password){
        return null;
    }
    private void save(){
    }
    private void load(){
    }
    private List getResult(){
        return null;
    }
}
